[package]
name = "day04"
version = "0.1.0"
authors = ["Andrew Dibble <acdibble@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
